### ISSUE TITLE
Add reading tracking

### ISSUE THREAD

**Issue by alessandrojean** [alessandrojean/tankobon#11]
### Describe your suggested feature

Implement in the client the read tracking, allowing users to mark books as reading or read.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version.
- [X] I filled out all of the requested information in this form.
